language: node_js
branches:
  only:
  - master
before_install:
  - git clone https://kelvingao:$PASSWORD@github.com/kelvingao/travis_encrypt.git
  - openssl aes-256-cbc -K $encrypted_eefb261b4d22_key -iv $encrypted_eefb261b4d22_iv
    -in travis_encrypt/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
install: true
script:
  - echo "skipping tests"
before_deploy:
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
notifications:
  email: false
